ext {
    junitVersion = project.hasProperty('junitVersion') ? rootProject.ext.junitVersion : '4.13.2'
}
buildscript {
    repositories { google(); mavenCentral() }
    dependencies { classpath 'com.android.tools.build:gradle:8.7.3' }
}
apply plugin: 'com.android.library'

android {
    namespace 'de.kayihaustechnik.scanner'
    compileSdk project.hasProperty('compileSdkVersion') ? rootProject.ext.compileSdkVersion : 35
    defaultConfig {
        minSdk project.hasProperty('minSdkVersion') ? rootProject.ext.minSdkVersion : 23
        targetSdk project.hasProperty('targetSdkVersion') ? rootProject.ext.targetSdkVersion : 35
        versionCode 1
        versionName '1.0.0'
        consumerProguardFiles 'consumer-rules.pro'
    }
    compileOptions { sourceCompatibility JavaVersion.VERSION_17; targetCompatibility JavaVersion.VERSION_17 }
}
repositories { google(); mavenCentral() }
dependencies {
    implementation project(':capacitor-android')
    implementation 'com.google.ar:core:1.54.0'
    implementation 'androidx.appcompat:appcompat:1.7.1'
    testImplementation "junit:junit:$junitVersion"
}
