# Generated by Django 5.2.16 on 2026-08-05

import decimal
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("erp", "0003_roommeasurement_measurementcapture"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="roommeasurement",
            new_name="erp_roommea_organiz_dd42ac_idx",
            old_name="erp_room_org_status_idx",
        ),
        migrations.RenameIndex(
            model_name="roommeasurement",
            new_name="erp_roommea_project_0cc128_idx",
            old_name="erp_room_proj_created_idx",
        ),
        migrations.AlterField(
            model_name="roommeasurement",
            name="confidence",
            field=models.DecimalField(
                decimal_places=4,
                default=0,
                max_digits=5,
                validators=[
                    django.core.validators.MinValueValidator(decimal.Decimal("0")),
                    django.core.validators.MaxValueValidator(decimal.Decimal("1")),
                ],
            ),
        ),
        migrations.AlterField(
            model_name="roommeasurement",
            name="deductions_area_m2",
            field=models.DecimalField(
                decimal_places=3,
                default=0,
                max_digits=10,
                validators=[
                    django.core.validators.MinValueValidator(decimal.Decimal("0")),
                ],
            ),
        ),
    ]
