# Generated by Django 5.2 for versioned editable room models.

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("erp", "0006_native_room_scan"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="RoomModelRevision",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("revision", models.PositiveIntegerField()),
                ("label", models.CharField(blank=True, max_length=160)),
                ("state", models.JSONField(default=dict)),
                ("created_by", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="created_room_model_revisions", to=settings.AUTH_USER_MODEL)),
                ("measurement", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="model_revisions", to="erp.roommeasurement")),
                ("organization", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="room_model_revisions", to="erp.organization")),
                ("project", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="room_model_revisions", to="erp.project")),
                ("source_scan", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="model_revisions", to="erp.nativeroomscan")),
            ],
            options={"ordering": ["-revision", "-created_at"]},
        ),
        migrations.AddConstraint(
            model_name="roommodelrevision",
            constraint=models.UniqueConstraint(fields=("measurement", "revision"), name="erp_room_model_measurement_revision_uniq"),
        ),
        migrations.AddIndex(
            model_name="roommodelrevision",
            index=models.Index(fields=["organization", "measurement", "revision"], name="erp_roommod_organiz_0cfda5_idx"),
        ),
    ]
