# Generated by Django 5.2.16 on 2026-08-06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("erp", "0007_room_model_revision"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="nativeroomscan",
            new_name="erp_nativer_organiz_1823cd_idx",
            old_name="erp_nativ_organiz_1f223e_idx",
        ),
        migrations.RenameIndex(
            model_name="nativeroomscan",
            new_name="erp_nativer_project_42e5d0_idx",
            old_name="erp_nativ_project_b9005d_idx",
        ),
    ]
