import { Capacitor, registerPlugin } from '@capacitor/core';

const Scanner = registerPlugin('KayiRoomScanner');
// Native navigation contract: data-route="scanner"
const API = 'https://kayi.smarbiz.sbs';
const OFFICE_ROLES = new Set(['admin', 'owner', 'manager', 'office', 'accounting']);
const state = {
  baseUrl: localStorage.getItem('ab.baseUrl') || API,
  token: localStorage.getItem('ab.token') || '',
  user: JSON.parse(localStorage.getItem('ab.user') || 'null'),
  route: 'home', data: {}, capabilities: null, loading: false,
  selectedCustomerId: null, selectedProjectId: null, selectedAppointmentId: null, selectedTaskId: null, selectedDocumentId: null, documentKind: 'quote', editingId: null,
  activeTimeEntry: null,
  online: navigator.onLine, lastSync: localStorage.getItem('ab.lastSync') || '',
};
const root = document.querySelector('#app');
const toastStack = document.querySelector('#toast-stack');
const esc = (value) => String(value ?? '').replace(/[&<>"']/g, (char) => ({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[char]));
const list = (payload) => Array.isArray(payload) ? payload : (payload?.results || []);
const isOffice = () => OFFICE_ROLES.has(state.user?.role);
const roleName = () => isOffice() ? 'Büro & Administration' : 'Mitarbeiter';
const fullName = () => state.user?.name || state.user?.username || 'A+Bau';
const cacheKey = () => `ab.cachedData.${state.user?.id || 'anonymous'}`;
function cachedOperationalData(){try{return JSON.parse(localStorage.getItem(cacheKey())||'null');}catch(_){localStorage.removeItem(cacheKey());return null;}}

function toast(message, type = 'success') {
  const node = document.createElement('div');
  node.className = `toast toast-${type}`;
  node.setAttribute('role', type === 'error' ? 'alert' : 'status');
  node.textContent = message;
  toastStack.append(node);
  setTimeout(() => node.remove(), 4500);
}

async function api(path, options = {}) {
  if (!navigator.onLine && !['GET','HEAD'].includes(options.method || 'GET')) throw new Error('Offline: Änderungen sind erst nach Wiederherstellung der Verbindung möglich.');
  const headers = {Accept:'application/json', ...(options.headers || {})};
  if (state.token) headers.Authorization = `Token ${state.token}`;
  let response;
  try { response = await fetch(state.baseUrl + path, {...options, headers}); }
  catch (_) { throw new Error('Server nicht erreichbar. Bitte Internetverbindung prüfen.'); }
  const body = response.status === 204 ? {} : await response.json().catch(() => ({}));
  if (response.status === 401) { logout(false); throw new Error('Sitzung abgelaufen. Bitte erneut anmelden.'); }
  if (!response.ok) throw new Error(body.detail || body.error || 'Aktion konnte nicht abgeschlossen werden.');
  return body;
}

async function login(event) {
  event.preventDefault();
  const form = event.currentTarget;
  setBusy(form, true, 'Anmeldung läuft …');
  try {
    state.baseUrl = form.server.value.replace(/\/$/, '');
    const data = await api('/api/mobile/login/', {method:'POST', headers:{'Content-Type':'application/json'}, body:JSON.stringify({username:form.username.value, password:form.password.value})});
    state.token = data.token; state.user = data.user;
    localStorage.setItem('ab.baseUrl', state.baseUrl); localStorage.setItem('ab.token', state.token); localStorage.setItem('ab.user', JSON.stringify(state.user));
    await bootstrap(); toast(`Willkommen, ${fullName()}.`);
  } catch (error) { setBusy(form, false, error.message, true); }
}

function setBusy(form, busy, message = '', error = false) {
  form?.setAttribute('aria-busy', String(busy));
  const button = form?.querySelector('button[type="submit"]'); if (button) button.disabled = busy;
  const status = form?.querySelector('[data-status]'); if (status) { status.textContent = message; status.className = `form-status${error ? ' is-error' : ''}`; }
}

async function bootstrap() {
  state.loading = true; renderShell();
  try {
    const common = [api('/api/projects/?ordering=-updated_at&page_size=100'), api('/api/events/?ordering=starts_at&page_size=100'), api('/api/tasks/?ordering=-created_at&page_size=100'), api('/api/time-entries/?ordering=-started_at&page_size=100')];
    const office = isOffice() ? [api('/api/customers/?ordering=-created_at&page_size=100'), api('/api/quotes/?ordering=-created_at&page_size=100'), api('/api/invoices/?ordering=-created_at&page_size=100'), api('/api/employees/?ordering=last_name&page_size=100'), api('/api/expenses/?ordering=-expense_date&page_size=100')] : [Promise.resolve([]), Promise.resolve([]), Promise.resolve([]), Promise.resolve([]), Promise.resolve([])];
    const [projects, events, tasks, timeEntries, customers, quotes, invoices, employees, expenses] = await Promise.all([...common, ...office]);
    state.data = {projects:list(projects), events:list(events), tasks:list(tasks), timeEntries:list(timeEntries), customers:list(customers), quotes:list(quotes), invoices:list(invoices), employees:list(employees), expenses:list(expenses)};
    state.activeTimeEntry = state.data.timeEntries.find(entry => !entry.ended_at) || null;
    state.lastSync = new Date().toISOString(); localStorage.setItem('ab.lastSync',state.lastSync); localStorage.setItem(cacheKey(),JSON.stringify({projects:state.data.projects,events:state.data.events,tasks:state.data.tasks,timeEntries:state.data.timeEntries,customers:[],quotes:[],invoices:[],employees:[],expenses:[]}));
    state.capabilities = await Scanner.getCapabilities().catch(() => ({supported:false, fallback:false, provider:'web'}));
    notifyUpcomingAppointments();
    state.loading = false; renderShell();
  } catch (error) { const cached=cachedOperationalData();if(cached){state.data=cached;state.activeTimeEntry=(cached.timeEntries||[]).find(entry=>!entry.ended_at)||null;state.loading=false;renderShell();toast('Offline-Modus: zuletzt synchronisierte Einsatzdaten werden angezeigt.','info');}else{state.loading=false;renderShell();toast(error.message,'error');} }
}

function notifyUpcomingAppointments(){const now=Date.now();for(const event of state.data.events||[]){const delta=new Date(event.starts_at).getTime()-now;const key=`ab.reminded.${event.id}.${String(event.starts_at)}`;if(delta>0&&delta<=2*60*60*1000&&!localStorage.getItem(key)){toast(`Termin in Kürze: ${event.title}`,'info');localStorage.setItem(key,'1');}}}
function connectionLabel(){if(!state.online)return '<span class="sync-chip offline">Offline</span>';if(!state.lastSync)return '<span class="sync-chip">Online</span>';return `<span class="sync-chip">Sync ${esc(new Date(state.lastSync).toLocaleTimeString('de-DE',{hour:'2-digit',minute:'2-digit'}))}</span>`;}

function renderLogin(message = '') {
  root.innerHTML = `<section class="login-screen"><div class="login-brand"><div class="brand-mark">A+</div><div><h1>A+Bau</h1><p>Die komplette Arbeit in einer App.</p></div></div><form class="login-card" id="login-form"><label>Server<input name="server" type="url" value="${esc(state.baseUrl)}" required></label><label>Benutzername<input name="username" autocomplete="username" required></label><label>Passwort<input name="password" type="password" autocomplete="current-password" required></label><button class="primary" type="submit">Anmelden</button><p class="form-status${message ? ' is-error' : ''}" data-status role="status">${esc(message || 'Mit deinem persönlichen A+Bau-Konto anmelden.')}</p></form></section>`;
  document.querySelector('#login-form').addEventListener('submit', login);
}

function navItems() {
  if (isOffice()) return [['home','⌂','Start'],['projects','▣','Projekte'],['appointments','◫','Termine'],['customers','◎','Kunden'],['more','•••','Mehr']];
  return [['home','⌂','Heute'],['appointments','◫','Einsätze'],['projects','▣','Projekte'],['time','◷','Zeit'],['more','•••','Mehr']];
}

function renderShell() {
  root.innerHTML = `<div class="app-shell"><header class="topbar"><div class="mini-brand"><span>A+</span><div><b>A+Bau</b><small>${esc(roleName())}</small></div></div><div class="topbar-actions">${connectionLabel()}<button class="avatar" data-route="profile" aria-label="Konto öffnen">${esc(fullName().slice(0,2).toUpperCase())}</button></div></header><section class="content">${state.loading ? loadingView() : renderRoute()}</section><nav class="bottom-nav" aria-label="Hauptnavigation">${navItems().map(([id,icon,label]) => `<button data-route="${id}" class="${state.route===id?'is-active':''}"><span>${icon}</span>${label}</button>`).join('')}</nav></div>`;
  bindActions();
}

const loadingView = () => '<section class="loading"><div class="spinner"></div><p>Arbeitsbereich wird synchronisiert …</p></section>';
function renderRoute() {
  const routes = {home:renderHome, projects:renderProjects, 'project-detail':renderProjectDetail, 'project-form':renderProjectForm, appointments:renderAppointments, 'appointment-detail':renderAppointmentDetail, 'appointment-form':renderAppointmentForm, 'work-report':renderWorkReport, customers:renderCustomers, 'customer-detail':renderCustomerDetail, 'customer-form':renderCustomerForm, time:renderTime, scanner:renderScanner, commercial:renderCommercial, quotes:()=>renderDocuments('quote'), invoices:()=>renderDocuments('invoice'), 'document-detail':renderDocumentDetail, 'document-form':renderDocumentForm, expenses:renderExpenses, 'expense-form':renderExpenseForm, tasks:renderTasks, 'task-detail':renderTaskDetail, more:renderMore, profile:renderProfile};
  return (routes[state.route] || renderHome)();
}

function pageHead(kicker, title, text, action = '') { return `<header class="page-head"><div><small>${esc(kicker)}</small><h1>${esc(title)}</h1><p>${esc(text)}</p></div>${action}</header>`; }
function metric(value, label, tone='') { return `<article class="metric ${tone}"><strong>${value}</strong><span>${esc(label)}</span></article>`; }
function renderHome() {
  const today = new Date().toISOString().slice(0,10);
  const todays = state.data.events.filter(x => String(x.starts_at || '').startsWith(today));
  const openTasks = state.data.tasks.filter(x => !['done','completed'].includes(x.status));
  if (isOffice()) return `${pageHead('OPERATIONS',`Guten Tag, ${fullName().split(' ')[0]}.`,'Kunden, Projekte und kaufmännische Arbeit auf einen Blick.','<button class="round-action" data-route="more">＋</button>')}<section class="metrics">${metric(state.data.projects.filter(x=>!['completed','cancelled'].includes(x.status)).length,'Aktive Projekte')}${metric(todays.length,'Termine heute','gold')}${metric(state.data.quotes.filter(x=>!['accepted','rejected'].includes(x.status)).length,'Offene Angebote')}${metric(state.data.invoices.filter(x=>!['paid','cancelled'].includes(x.status)).length,'Offene Rechnungen','danger')}</section>${agenda(todays)}${quickActions(true)}`;
  return `${pageHead('MEINE ARBEIT',`Hallo, ${fullName().split(' ')[0]}.`,'Deine Einsätze, Aufgaben, Zeiten und Projektdaten.')}<section class="metrics two">${metric(todays.length,'Einsätze heute','gold')}${metric(openTasks.length,'Offene Aufgaben')}</section>${agenda(todays)}${quickActions(false)}`;
}

function agenda(events) { return `<section class="panel"><header><h2>Heute</h2><button data-route="appointments">Alle Termine</button></header><div class="rows">${events.slice(0,5).map(eventRow).join('') || '<div class="empty">Heute sind keine Termine eingetragen.</div>'}</div></section>`; }
function eventRow(item) { const time = item.starts_at ? new Date(item.starts_at).toLocaleTimeString('de-DE',{hour:'2-digit',minute:'2-digit'}) : '—'; return `<button class="row row-button" data-appointment-id="${item.id}"><time>${esc(time)}</time><div><b>${esc(item.title)}</b><small>${esc(item.location || projectName(item.project) || 'Kein Ort')}</small></div><span>›</span></button>`; }
function quickActions(office) { const actions = office ? [['customers','◎','Kunde'],['projects','▣','Projekt'],['appointments','◫','Termin'],['commercial','€','Angebot']] : [['time','◷','Zeit'],['scanner','⌗','Aufmaß'],['tasks','✓','Aufgaben'],['projects','▣','Projekte']]; return `<section class="quick-grid">${actions.map(([route,icon,label])=>`<button data-route="${route}"><span>${icon}</span><b>${label}</b></button>`).join('')}</section>`; }

function renderProjects() { const action=isOffice()?'<button class="round-action" data-new-project aria-label="Neues Projekt">＋</button>':''; return `${pageHead('PROJEKTE', isOffice()?'Alle Projekte':'Meine Projekte', isOffice()?'Aktive Aufträge und Projektstatus.':'Nur dir zugewiesene Projekte.',action)}<div class="rows cards">${state.data.projects.map(p=>`<article class="project-card"><button class="card-open" data-project-id="${p.id}" aria-label="Projekt ${esc(p.title)} öffnen"><header><span>${esc(p.number || 'PROJEKT')}</span><em>${esc(p.status || '')}</em></header><h2>${esc(p.title)}</h2><p>${esc(p.customer_name || p.description || '')}</p></button><footer><button data-scan-project="${p.id}">⌗ Raum aufmessen</button></footer></article>`).join('') || '<div class="empty">Keine Projekte verfügbar.</div>'}</div>`; }
function projectName(id){return state.data.projects.find(p=>Number(p.id)===Number(id))?.title||'';}
function employeeName(id){const e=state.data.employees?.find(row=>Number(row.id)===Number(id));return e?[e.first_name,e.last_name].filter(Boolean).join(' ')||e.employee_number:'';}
function selectedAppointment(){return state.data.events.find(item=>Number(item.id)===Number(state.selectedAppointmentId));}
function selectedTask(){return state.data.tasks.find(item=>Number(item.id)===Number(state.selectedTaskId));}
function localDateTime(value){if(!value)return '';const date=new Date(value);const pad=n=>String(n).padStart(2,'0');return `${date.getFullYear()}-${pad(date.getMonth()+1)}-${pad(date.getDate())}T${pad(date.getHours())}:${pad(date.getMinutes())}`;}
function displayDateTime(value){return value?new Date(value).toLocaleString('de-DE',{dateStyle:'medium',timeStyle:'short'}):'—';}
function renderAppointments() { const action=isOffice()?'<button class="round-action" data-new-appointment aria-label="Neuer Termin">＋</button>':'';return `${pageHead('KALENDER',isOffice()?'Termine & Einsätze':'Meine Einsätze',isOffice()?'Planung für Team und Baustellen.':'Deine zugewiesenen Termine.',action)}<div class="rows cards">${state.data.events.map(eventRow).join('') || '<div class="empty">Keine Termine verfügbar.</div>'}</div>`; }
function renderAppointmentDetail(){const e=selectedAppointment();if(!e)return forbidden();const attendees=(e.attendees||[]).map(employeeName).filter(Boolean);const action=isOffice()?'<button class="secondary compact" data-edit-appointment>Bearbeiten</button>':'';return `${pageHead('TERMIN',e.title,e.type||'',action)}<section class="detail-card"><dl><div><dt>Beginn</dt><dd>${esc(displayDateTime(e.starts_at))}</dd></div><div><dt>Ende</dt><dd>${esc(displayDateTime(e.ends_at))}</dd></div><div><dt>Projekt</dt><dd>${esc(projectName(e.project)||'—')}</dd></div><div><dt>Ort</dt><dd>${e.location?`<a href="https://maps.apple.com/?q=${encodeURIComponent(e.location)}">${esc(e.location)}</a>`:'—'}</dd></div><div><dt>Team</dt><dd>${esc(attendees.join(', ')||'—')}</dd></div><div><dt>Notizen</dt><dd>${esc(e.notes||'—')}</dd></div><div><dt>Arbeitsbericht</dt><dd>${esc(e.work_report||'Noch nicht erfasst.')}</dd></div></dl><div class="detail-actions"><button class="secondary" data-work-report>Arbeitsbericht</button>${e.location?'<button class="secondary" data-open-map>Navigation</button>':''}</div></section>`;}
function renderAppointmentForm(){if(!isOffice())return forbidden();const e=state.editingId?state.data.events.find(x=>Number(x.id)===Number(state.editingId)):null;const selected=new Set((e?.attendees||[]).map(Number));return `${pageHead('TERMIN',e?'Termin bearbeiten':'Neuer Termin','Einsatz, Zeitraum und Team verbindlich planen.')}<form class="entity-form" data-appointment-form><div class="form-grid"><label class="wide">Titel<input name="title" value="${esc(e?.title||'')}" required></label><label>Art<select name="type">${[['appointment','Termin'],['site','Baustelle'],['inspection','Besichtigung'],['delivery','Lieferung'],['internal','Intern']].map(([v,l])=>`<option value="${v}" ${e?.type===v?'selected':''}>${l}</option>`).join('')}</select></label><label>Projekt<select name="project"><option value="">Ohne Projekt</option>${state.data.projects.map(p=>`<option value="${p.id}" ${Number(e?.project)===Number(p.id)?'selected':''}>${esc(p.title)}</option>`).join('')}</select></label><label>Beginn<input name="starts_at" type="datetime-local" value="${esc(localDateTime(e?.starts_at))}" required></label><label>Ende<input name="ends_at" type="datetime-local" value="${esc(localDateTime(e?.ends_at))}" required></label><label class="wide">Ort<input name="location" value="${esc(e?.location||'')}"></label><label class="wide">Mitarbeiter<select name="attendees" multiple size="${Math.min(6,Math.max(3,state.data.employees?.length||3))}">${(state.data.employees||[]).map(emp=>`<option value="${emp.id}" ${selected.has(Number(emp.id))?'selected':''}>${esc([emp.first_name,emp.last_name].filter(Boolean).join(' ')||emp.employee_number)}</option>`).join('')}</select><small>Mehrfachauswahl möglich.</small></label><label class="wide">Notizen<textarea name="notes" rows="4">${esc(e?.notes||'')}</textarea></label></div><button class="primary" type="submit">${e?'Änderungen speichern':'Termin anlegen'}</button><button class="secondary" type="button" data-cancel-appointment>Abbrechen</button></form>`;}
function renderWorkReport(){const e=selectedAppointment();if(!e)return forbidden();return `${pageHead('ARBEITSBERICHT',e.title,'Dokumentation des ausgeführten Einsatzes.')}<form class="entity-form" data-work-report-form><label>Ausgeführte Arbeiten<textarea name="work_report" rows="9" required placeholder="Was wurde vor Ort erledigt?">${esc(e.work_report||'')}</textarea></label><button class="primary" type="submit">Arbeitsbericht speichern</button><button class="secondary" type="button" data-cancel-report>Abbrechen</button></form>`;}
function renderCustomers() { if (!isOffice()) return forbidden(); return `${pageHead('STAMMDATEN','Kunden','Kontakte und zugehörige Projekte.','<button class="round-action" data-new-customer aria-label="Neuer Kunde">＋</button>')}<div class="rows cards">${state.data.customers.map(c=>`<button class="row row-button" data-customer-id="${c.id}"><span class="circle">${esc((c.company||c.last_name||'?').slice(0,1))}</span><div><b>${esc(c.display_name || c.company || `${c.first_name||''} ${c.last_name||''}`)}</b><small>${esc(c.number || c.email || c.phone || '')}</small></div><span>›</span></button>`).join('') || '<div class="empty">Keine Kunden vorhanden.</div>'}</div>`; }

function selectedCustomer(){return state.data.customers.find(item=>Number(item.id)===Number(state.selectedCustomerId));}
function selectedProject(){return state.data.projects.find(item=>Number(item.id)===Number(state.selectedProjectId));}
function detailActions(kind){if(!isOffice())return '';return `<button class="secondary compact" data-edit-${kind}>Bearbeiten</button>`;}
function renderCustomerDetail(){const c=selectedCustomer();if(!c)return forbidden();const projects=state.data.projects.filter(p=>Number(p.customer)===Number(c.id));return `${pageHead('KUNDE',c.display_name||c.company||`${c.first_name||''} ${c.last_name||''}`,c.number||'',detailActions('customer'))}<section class="detail-card"><dl><div><dt>Firma</dt><dd>${esc(c.company||'—')}</dd></div><div><dt>Ansprechpartner</dt><dd>${esc(`${c.first_name||''} ${c.last_name||''}`.trim()||'—')}</dd></div><div><dt>E-Mail</dt><dd>${c.email?`<a href="mailto:${esc(c.email)}">${esc(c.email)}</a>`:'—'}</dd></div><div><dt>Telefon</dt><dd>${c.phone?`<a href="tel:${esc(c.phone)}">${esc(c.phone)}</a>`:'—'}</dd></div><div><dt>Adresse</dt><dd>${esc([c.street,c.postal_code,c.city].filter(Boolean).join(', ')||'—')}</dd></div><div><dt>Notizen</dt><dd>${esc(c.notes||'—')}</dd></div></dl></section><section class="panel"><header><h2>Projekte</h2>${isOffice()?'<button data-new-project-for-customer>Projekt anlegen</button>':''}</header><div class="rows">${projects.map(p=>`<button class="row row-button" data-project-id="${p.id}"><span class="circle">▣</span><div><b>${esc(p.title)}</b><small>${esc(p.number||p.status||'')}</small></div><span>›</span></button>`).join('')||'<div class="empty">Noch keine Projekte.</div>'}</div></section>`;}
function renderCustomerForm(){if(!isOffice())return forbidden();const c=state.editingId?state.data.customers.find(x=>Number(x.id)===Number(state.editingId)):null;return `${pageHead('KUNDE',c?'Kunde bearbeiten':'Neuer Kunde','Stammdaten vollständig und korrekt erfassen.')}<form class="entity-form" data-customer-form><div class="form-grid"><label>Kundentyp<select name="type"><option value="private" ${c?.type==='private'?'selected':''}>Privatkunde</option><option value="business" ${c?.type==='business'?'selected':''}>Geschäftskunde</option><option value="insurance" ${c?.type==='insurance'?'selected':''}>Versicherung</option><option value="property_manager" ${c?.type==='property_manager'?'selected':''}>Hausverwaltung</option></select></label><label>Firma<input name="company" value="${esc(c?.company||'')}"></label><label>Vorname<input name="first_name" value="${esc(c?.first_name||'')}"></label><label>Nachname<input name="last_name" value="${esc(c?.last_name||'')}"></label><label>E-Mail<input name="email" type="email" value="${esc(c?.email||'')}"></label><label>Telefon<input name="phone" type="tel" value="${esc(c?.phone||'')}"></label><label class="wide">Straße<input name="street" value="${esc(c?.street||'')}"></label><label>PLZ<input name="postal_code" value="${esc(c?.postal_code||'')}"></label><label>Ort<input name="city" value="${esc(c?.city||'')}"></label><label class="wide">Notizen<textarea name="notes" rows="4">${esc(c?.notes||'')}</textarea></label></div><p class="form-hint">Mindestens Firma oder Vor-/Nachname eintragen.</p><button class="primary" type="submit">${c?'Änderungen speichern':'Kunde anlegen'}</button><button class="secondary" type="button" data-cancel-entity>Abbrechen</button></form>`;}

function renderProjectDetail(){const p=selectedProject();if(!p)return forbidden();const customer=state.data.customers.find(c=>Number(c.id)===Number(p.customer));return `${pageHead('PROJEKT',p.title,p.number||'',detailActions('project'))}<section class="detail-card"><dl><div><dt>Kunde</dt><dd>${esc(p.customer_name||customer?.display_name||'—')}</dd></div><div><dt>Status</dt><dd>${esc(p.status||'—')}</dd></div><div><dt>Priorität</dt><dd>${esc(p.priority||'—')}</dd></div><div><dt>Zeitraum</dt><dd>${esc([p.planned_start,p.planned_end].filter(Boolean).join(' – ')||'—')}</dd></div><div><dt>Beschreibung</dt><dd>${esc(p.description||'—')}</dd></div></dl><div class="detail-actions"><button class="secondary" data-scan-project="${p.id}">⌗ Raum aufmessen</button><button class="secondary" data-route="appointments">◫ Termine</button></div></section>`;}
function renderProjectForm(){if(!isOffice())return forbidden();const p=state.editingId?state.data.projects.find(x=>Number(x.id)===Number(state.editingId)):null;const preset=state.selectedCustomerId||p?.customer||'';return `${pageHead('PROJEKT',p?'Projekt bearbeiten':'Neues Projekt','Kunde, Status und Ausführungsdaten festlegen.')}<form class="entity-form" data-project-form><div class="form-grid"><label class="wide">Titel<input name="title" value="${esc(p?.title||'')}" required></label><label class="wide">Kunde<select name="customer" required><option value="">Kunde auswählen</option>${state.data.customers.map(c=>`<option value="${c.id}" ${Number(c.id)===Number(preset)?'selected':''}>${esc(c.display_name||c.company||c.number)}</option>`).join('')}</select></label><label>Auftragsart<select name="job_type"><option value="private" ${p?.job_type!=='insurance'?'selected':''}>Privatauftrag</option><option value="insurance" ${p?.job_type==='insurance'?'selected':''}>Versicherung / B&amp;O</option></select></label><label>Status<select name="status">${[['inquiry','Anfrage'],['planning','Planung'],['quoted','Angebot'],['confirmed','Beauftragt'],['in_progress','In Ausführung'],['waiting','Wartet'],['review','Abnahme'],['invoiced','Abgerechnet'],['completed','Abgeschlossen'],['cancelled','Storniert']].map(([v,l])=>`<option value="${v}" ${p?.status===v?'selected':''}>${l}</option>`).join('')}</select></label><label>Priorität<select name="priority">${[['low','Niedrig'],['normal','Normal'],['high','Hoch'],['urgent','Dringend']].map(([v,l])=>`<option value="${v}" ${(p?.priority||'normal')===v?'selected':''}>${l}</option>`).join('')}</select></label><label>Start<input name="planned_start" type="date" value="${esc(p?.planned_start||'')}"></label><label>Ende<input name="planned_end" type="date" value="${esc(p?.planned_end||'')}"></label><label class="wide">Beschreibung<textarea name="description" rows="5">${esc(p?.description||'')}</textarea></label></div><button class="primary" type="submit">${p?'Änderungen speichern':'Projekt anlegen'}</button><button class="secondary" type="button" data-cancel-entity>Abbrechen</button></form>`;}
function renderTasks() { return `${pageHead('AUFGABEN',isOffice()?'Team-Aufgaben':'Meine Aufgaben','Offene Punkte für die Ausführung.')}<div class="rows cards">${state.data.tasks.map(t=>`<button class="row row-button" data-task-id="${t.id}"><span class="task-dot ${esc(t.priority||'')}"></span><div><b>${esc(t.title)}</b><small>${esc(projectName(t.project) || t.status || '')}</small></div><span>›</span></button>`).join('') || '<div class="empty">Keine Aufgaben vorhanden.</div>'}</div>`; }
function renderTaskDetail(){const t=selectedTask();if(!t)return forbidden();const labels={open:'Offen',in_progress:'In Arbeit',done:'Erledigt',completed:'Erledigt'};return `${pageHead('AUFGABE',t.title,labels[t.status]||t.status||'')}<section class="detail-card"><dl><div><dt>Projekt</dt><dd>${esc(projectName(t.project)||'—')}</dd></div><div><dt>Priorität</dt><dd>${esc(t.priority||'—')}</dd></div><div><dt>Fällig</dt><dd>${esc(displayDateTime(t.due_at))}</dd></div><div><dt>Beschreibung</dt><dd>${esc(t.description||'—')}</dd></div></dl><div class="status-actions"><button data-task-status="open" class="secondary ${t.status==='open'?'is-current':''}">Offen</button><button data-task-status="in_progress" class="secondary ${t.status==='in_progress'?'is-current':''}">In Arbeit</button><button data-task-status="done" class="secondary ${['done','completed'].includes(t.status)?'is-current':''}">Erledigt</button></div></section>`;}
const money=value=>Number(value||0).toLocaleString('de-DE',{style:'currency',currency:'EUR'});
function documentCollection(){return state.documentKind==='invoice'?state.data.invoices:state.data.quotes;}
function selectedDocument(){return documentCollection().find(row=>Number(row.id)===Number(state.selectedDocumentId));}
function renderCommercial() { if(!isOffice()) return forbidden();const openInvoices=state.data.invoices.filter(i=>!['paid','cancelled'].includes(i.status));const outstanding=openInvoices.reduce((sum,i)=>sum+Number(i.outstanding_total||0),0);return `${pageHead('KAUFMÄNNISCH','Finanzen','Angebote, Rechnungen und Ausgaben zentral bearbeiten.')}<section class="metrics two">${metric(state.data.quotes.length,'Angebote','gold')}${metric(money(outstanding),'Offener Betrag','danger')}</section><section class="menu-list"><button data-route="quotes"><span>◇</span><div><b>Angebote</b><small>Erstellen, prüfen und verwalten</small></div><em>${state.data.quotes.length}</em></button><button data-route="invoices"><span>€</span><div><b>Rechnungen</b><small>Fälligkeiten und Zahlstatus</small></div><em>${state.data.invoices.length}</em></button><button data-route="expenses"><span>↘</span><div><b>Ausgaben</b><small>Belege und Projektkosten</small></div><em>${state.data.expenses.length}</em></button></section>`; }
function renderDocuments(kind){if(!isOffice())return forbidden();state.documentKind=kind;const invoice=kind==='invoice';const rows=invoice?state.data.invoices:state.data.quotes;return `${pageHead('KAUFMÄNNISCH',invoice?'Rechnungen':'Angebote',invoice?'Offene Beträge, Fälligkeit und Status.':'Leistungen kalkulieren und Angebote verwalten.','<button class="round-action" data-new-document aria-label="Neues Dokument">＋</button>')}<div class="rows cards">${rows.map(d=>`<button class="document-row" data-document-id="${d.id}"><div><small>${esc(d.number||'ENTWURF')}</small><b>${esc(projectName(d.project)||'Ohne Projekt')}</b><span>${esc(d.status||'draft')}</span></div><strong>${money(invoice?d.outstanding_total:d.gross_total)}</strong></button>`).join('')||'<div class="empty">Noch keine Dokumente vorhanden.</div>'}</div>`;}
function renderDocumentDetail(){if(!isOffice())return forbidden();const d=selectedDocument();if(!d)return forbidden();const invoice=state.documentKind==='invoice';return `${pageHead(invoice?'RECHNUNG':'ANGEBOT',d.number||'Entwurf',projectName(d.project)||'',`<button class="secondary compact" data-edit-document>Bearbeiten</button>`)}<section class="detail-card"><dl><div><dt>Status</dt><dd>${esc(d.status||'draft')}</dd></div><div><dt>Datum</dt><dd>${esc(d.issue_date||'—')}</dd></div>${invoice?`<div><dt>Fällig</dt><dd>${esc(d.due_date||'—')}</dd></div>`:`<div><dt>Gültig bis</dt><dd>${esc(d.valid_until||'—')}</dd></div>`}<div><dt>Netto</dt><dd>${money(d.net_total)}</dd></div><div><dt>Steuer</dt><dd>${money(d.tax_total)}</dd></div><div><dt>Gesamt</dt><dd>${money(d.gross_total)}</dd></div>${invoice?`<div><dt>Offen</dt><dd>${money(d.outstanding_total)}</dd></div>`:''}<div><dt>Notizen</dt><dd>${esc(d.notes||'—')}</dd></div></dl></section><section class="panel"><header><h2>Positionen</h2></header><div class="position-list">${(d.items||[]).map(item=>`<div><span>${esc(item.quantity)} ${esc(item.unit)} × ${money(item.unit_price)}</span><b>${esc(item.description)}</b><strong>${money(item.net_total)}</strong></div>`).join('')||'<div class="empty">Keine Positionen.</div>'}</div></section>`;}
function positionEditor(item={}){return `<div class="position-edit"><label class="description">Leistung<input name="item_description" value="${esc(item.description||'')}" required></label><label>Menge<input name="item_quantity" type="number" min="0.001" step="0.001" value="${esc(item.quantity||1)}" required></label><label>Einheit<input name="item_unit" value="${esc(item.unit||'Stk.')}" required></label><label>Einzelpreis netto<input name="item_unit_price" type="number" min="0" step="0.01" value="${esc(item.unit_price||0)}" required></label><label>MwSt. %<input name="item_tax_rate" type="number" min="0" step="0.01" value="${esc(item.tax_rate??19)}" required></label><button type="button" class="remove-position" data-remove-position aria-label="Position entfernen">×</button></div>`;}
function renderDocumentForm(){if(!isOffice())return forbidden();const d=state.editingId?documentCollection().find(x=>Number(x.id)===Number(state.editingId)):null;const invoice=state.documentKind==='invoice';const today=new Date().toISOString().slice(0,10);const future=new Date(Date.now()+14*86400000).toISOString().slice(0,10);return `${pageHead(invoice?'RECHNUNG':'ANGEBOT',d?'Dokument bearbeiten':invoice?'Neue Rechnung':'Neues Angebot','Projekt, Fristen und Positionen vollständig erfassen.')}<form class="entity-form" data-document-form><div class="form-grid"><label class="wide">Projekt<select name="project" required><option value="">Projekt auswählen</option>${state.data.projects.map(p=>`<option value="${p.id}" ${Number(d?.project)===Number(p.id)?'selected':''}>${esc(p.number||'')} · ${esc(p.title)}</option>`).join('')}</select></label><label>Status<select name="status">${(invoice?[['draft','Entwurf'],['review','Prüfung'],['sent','Gesendet'],['partial','Teilbezahlt'],['paid','Bezahlt'],['cancelled','Storniert']]:[['draft','Entwurf'],['review','Prüfung'],['sent','Gesendet'],['accepted','Angenommen'],['rejected','Abgelehnt'],['expired','Abgelaufen']]).map(([v,l])=>`<option value="${v}" ${d?.status===v?'selected':''}>${l}</option>`).join('')}</select></label><label>Datum<input name="issue_date" type="date" value="${esc(d?.issue_date||today)}" required></label><label>${invoice?'Fällig am':'Gültig bis'}<input name="${invoice?'due_date':'valid_until'}" type="date" value="${esc((invoice?d?.due_date:d?.valid_until)||future)}" required></label><label class="wide">Einleitung<textarea name="intro_text" rows="3">${esc(d?.intro_text||'')}</textarea></label></div><section class="position-editor"><header><h2>Positionen</h2><button type="button" data-add-position>＋ Position</button></header><div data-positions>${(d?.items?.length?d.items:[{}]).map(positionEditor).join('')}</div></section><label>Notizen<textarea name="notes" rows="3">${esc(d?.notes||'')}</textarea></label><button class="primary" type="submit">${d?'Änderungen speichern':'Dokument anlegen'}</button><button class="secondary" type="button" data-cancel-document>Abbrechen</button></form>`;}
function renderExpenses(){if(!isOffice())return forbidden();return `${pageHead('AUSGABEN','Projektkosten','Lieferantenrechnungen und sonstige Kosten.','<button class="round-action" data-new-expense>＋</button>')}<div class="rows cards">${state.data.expenses.map(e=>`<article class="document-row"><div><small>${esc(e.expense_date||'')}</small><b>${esc(e.supplier)}</b><span>${esc(e.description)}</span></div><strong>${money(e.amount_gross)}</strong></article>`).join('')||'<div class="empty">Noch keine Ausgaben erfasst.</div>'}</div>`;}
function renderExpenseForm(){if(!isOffice())return forbidden();const today=new Date().toISOString().slice(0,10);return `${pageHead('AUSGABE','Neue Ausgabe','Kosten einem Projekt und Lieferanten zuordnen.')}<form class="entity-form" data-expense-form><div class="form-grid"><label>Lieferant<input name="supplier" required></label><label>Datum<input name="expense_date" type="date" value="${today}" required></label><label class="wide">Beschreibung<input name="description" required></label><label>Projekt<select name="project"><option value="">Ohne Projekt</option>${state.data.projects.map(p=>`<option value="${p.id}">${esc(p.title)}</option>`).join('')}</select></label><label>Kategorie<input name="category" placeholder="Material, Fahrt …"></label><label>Nettobetrag<input name="amount_net" type="number" min="0" step="0.01" required></label><label>MwSt. %<input name="tax_rate" type="number" min="0" step="0.01" value="19" required></label><label class="check-label"><input name="paid" type="checkbox"> Bereits bezahlt</label></div><button class="primary" type="submit">Ausgabe speichern</button><button class="secondary" type="button" data-route="expenses">Abbrechen</button></form>`;}
function renderTime() { const active=state.activeTimeEntry;if(active)return `${pageHead('ZEITERFASSUNG','Arbeitszeit läuft','Beende den Einsatz erst, wenn die Arbeit abgeschlossen ist.')}<form class="time-card" data-time-stop-form><div class="time-icon live">◷</div><h2>${esc(projectName(active.project)||'Laufender Einsatz')}</h2><p>Gestartet: ${esc(displayDateTime(active.started_at))}</p><label>Pausenminuten<input name="break_minutes" type="number" min="0" value="0"></label><label>Abschlussnotiz<textarea name="description" rows="3">${esc(active.description||'')}</textarea></label><button class="danger" type="submit">Arbeit stoppen</button></form>${renderTimeHistory()}`;return `${pageHead('ZEITERFASSUNG','Arbeitszeit','Start und Stopp werden projektbezogen protokolliert.')}<form class="time-card" data-time-start-form><div class="time-icon">◷</div><h2>Bereit für den nächsten Einsatz?</h2><label>Projekt<select name="project_id" required><option value="">Projekt auswählen</option>${state.data.projects.map(p=>`<option value="${p.id}">${esc(p.number||'')} · ${esc(p.title)}</option>`).join('')}</select></label><label>Beschreibung<textarea name="description" rows="3" placeholder="Tätigkeit oder Einsatz"></textarea></label><button class="primary" type="submit">Arbeit starten</button></form>${renderTimeHistory()}`; }
function renderTimeHistory(){const rows=(state.data.timeEntries||[]).filter(e=>e.ended_at).slice(0,10);return `<section class="panel"><header><h2>Letzte Zeiten</h2></header><div class="rows">${rows.map(e=>`<article class="row"><time>${esc(new Date(e.started_at).toLocaleDateString('de-DE',{day:'2-digit',month:'2-digit'}))}</time><div><b>${esc(projectName(e.project)||'Arbeitszeit')}</b><small>${esc(e.duration_minutes!=null?`${e.duration_minutes} Min.`:displayDateTime(e.ended_at))}</small></div></article>`).join('')||'<div class="empty">Noch keine abgeschlossenen Zeiten.</div>'}</div></section>`;}
function renderScanner() { const caps=state.capabilities||{}; return `${pageHead('AUFMASS','Raum erfassen','Der Scanner ist ein Werkzeug innerhalb des vollständigen A+Bau-Workflows.')}<section class="scan-card"><span class="scan-icon">⌗</span><h2>${caps.lidar?'LiDAR bereit':caps.fallback?'Manuelles Aufmaß verfügbar':caps.supported?'Scanner bereit':'Scanner nicht verfügbar'}</h2><p>${esc(caps.provider || Capacitor.getPlatform())}</p><label>Projekt<select id="scan-project"><option value="">Projekt auswählen</option>${state.data.projects.map(p=>`<option value="${p.id}">${esc(p.number)} · ${esc(p.title)}</option>`).join('')}</select></label><button class="primary" data-start-scan ${caps.supported?'':'disabled'}>Raum scannen</button><button class="secondary" data-pending-scans>Nicht hochgeladene Scans</button><div data-scan-result></div></section>`; }
function renderMore() { const office = isOffice(); const items = office ? [['customers','◎','Kunden'],['commercial','€','Angebote & Rechnungen'],['tasks','✓','Aufgaben'],['scanner','⌗','Aufmaß & Scanner'],['profile','⚙','Konto & Einstellungen']] : [['tasks','✓','Aufgaben'],['scanner','⌗','Aufmaß & Scanner'],['profile','⚙','Konto']]; return `${pageHead('MENÜ','Alle Bereiche','Funktionen passend zu deiner Rolle.')}<section class="menu-list">${items.map(([route,icon,title])=>`<button data-route="${route}"><span>${icon}</span><div><b>${title}</b><small>Öffnen</small></div><em>›</em></button>`).join('')}</section>`; }
function renderProfile() { return `${pageHead('KONTO',fullName(),roleName())}<section class="profile-card"><dl><div><dt>Benutzer</dt><dd>${esc(state.user?.username)}</dd></div><div><dt>Organisation</dt><dd>${esc(state.user?.organization || 'A+Bau')}</dd></div><div><dt>Rolle</dt><dd>${esc(roleName())}</dd></div></dl><button class="danger" data-logout>Abmelden</button></section>`; }
const forbidden = () => `${pageHead('BERECHTIGUNG','Nicht verfügbar','Dieser Bereich ist für deine Rolle nicht freigeschaltet.')}<button class="secondary" data-route="home">Zurück zur Startseite</button>`;

function clearScannerFeedback(){const target=document.querySelector('[data-scan-result]');if(target)target.replaceChildren();}
async function startScan(projectId){clearScannerFeedback();
  if (!projectId) return toast('Bitte zuerst ein Projekt auswählen.', 'error');
  toast('Aufmaß wird geöffnet …', 'info');
  try { const scan=await Scanner.startScan({roomName:'Raum'}); await Scanner.uploadScan({scanId:scan.scanId,projectId:Number(projectId),apiBaseUrl:state.baseUrl,token:state.token}); toast('Aufmaß gespeichert und zur Prüfung hochgeladen.'); }
  catch(error) { toast(error.message || String(error), 'error'); }
}
async function listPending(){clearScannerFeedback();try { const data=await Scanner.listPendingScans(); const scans=list(data?.scans || data); const target=document.querySelector('[data-scan-result]'); target.innerHTML=scans.length?`<ul class="pending-list">${scans.map(s=>`<li>${esc(s.roomName||'Raumaufmaß')}<small>${esc(s.createdAt||'Lokal gespeichert')}</small></li>`).join('')}</ul>`:'<p class="empty">Keine nicht hochgeladenen Scans vorhanden.</p>'; } catch(error){toast(error.message,'error');} }
async function logout(callApi=true) { const oldCache=cacheKey();if(callApi) await api('/api/mobile/logout/',{method:'POST'}).catch(()=>{}); state.token='';state.user=null;localStorage.removeItem('ab.token');localStorage.removeItem('ab.user');localStorage.removeItem(oldCache);localStorage.removeItem('ab.lastSync');renderLogin(); }

function formPayload(form){return Object.fromEntries([...new FormData(form).entries()].map(([key,value])=>[key,String(value).trim()]));}
function upsert(collection,item){const index=collection.findIndex(row=>Number(row.id)===Number(item.id));if(index>=0)collection[index]=item;else collection.unshift(item);}
async function saveCustomer(event){event.preventDefault();const form=event.currentTarget;const payload=formPayload(form);if(!payload.company&&!payload.first_name&&!payload.last_name){toast('Bitte Firma oder einen Namen eintragen.','error');form.querySelector('[name="company"]')?.focus();return;}setBusy(form,true,'Kunde wird gespeichert …');try{const id=state.editingId;const saved=await api(`/api/customers/${id?`${id}/`:''}`,{method:id?'PATCH':'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(payload)});upsert(state.data.customers,saved);state.selectedCustomerId=saved.id;state.editingId=null;state.route='customer-detail';renderShell();toast(id?'Kundendaten wurden gespeichert.':'Kunde wurde angelegt.');}catch(error){setBusy(form,false,error.message,true);toast(error.message,'error');}}
async function saveProject(event){event.preventDefault();const form=event.currentTarget;const payload=formPayload(form);payload.customer=Number(payload.customer);for(const key of ['planned_start','planned_end'])if(!payload[key])delete payload[key];setBusy(form,true,'Projekt wird gespeichert …');try{const id=state.editingId;const saved=await api(`/api/projects/${id?`${id}/`:''}`,{method:id?'PATCH':'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(payload)});upsert(state.data.projects,saved);state.selectedProjectId=saved.id;state.editingId=null;state.route='project-detail';renderShell();toast(id?'Projekt wurde gespeichert.':'Projekt wurde angelegt.');}catch(error){setBusy(form,false,error.message,true);toast(error.message,'error');}}
async function saveAppointment(event){event.preventDefault();const form=event.currentTarget;const payload=formPayload(form);payload.attendees=new FormData(form).getAll('attendees').map(Number);if(payload.project)payload.project=Number(payload.project);else payload.project=null;if(new Date(payload.ends_at)<=new Date(payload.starts_at)){toast('Das Ende muss nach dem Beginn liegen.','error');form.querySelector('[name="ends_at"]')?.focus();return;}setBusy(form,true,'Termin wird gespeichert …');try{const id=state.editingId;const saved=await api(`/api/events/${id?`${id}/`:''}`,{method:id?'PATCH':'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(payload)});upsert(state.data.events,saved);state.selectedAppointmentId=saved.id;state.editingId=null;state.route='appointment-detail';renderShell();toast(id?'Termin wurde aktualisiert.':'Termin wurde angelegt.');}catch(error){setBusy(form,false,error.message,true);toast(error.message,'error');}}
async function saveWorkReport(event){event.preventDefault();const form=event.currentTarget;const report=String(new FormData(form).get('work_report')||'').trim();if(!report){toast('Bitte den Arbeitsbericht ausfüllen.','error');return;}setBusy(form,true,'Arbeitsbericht wird gespeichert …');try{const saved=await api(`/api/mobile/appointments/${state.selectedAppointmentId}/work-report/`,{method:'PATCH',headers:{'Content-Type':'application/json'},body:JSON.stringify({work_report:report})});upsert(state.data.events,saved);state.route='appointment-detail';renderShell();toast('Arbeitsbericht wurde gespeichert.');}catch(error){setBusy(form,false,error.message,true);toast(error.message,'error');}}
async function updateTaskStatus(statusValue){const task=selectedTask();if(!task)return;try{const saved=await api(`/api/tasks/${task.id}/`,{method:'PATCH',headers:{'Content-Type':'application/json'},body:JSON.stringify({status:statusValue})});upsert(state.data.tasks,saved);renderShell();toast(statusValue==='done'?'Aufgabe wurde erledigt.':'Aufgabenstatus wurde aktualisiert.');}catch(error){toast(error.message,'error');}}
async function startTime(event){event.preventDefault();const form=event.currentTarget;const payload=formPayload(form);payload.project_id=Number(payload.project_id);setBusy(form,true,'Arbeitszeit wird gestartet …');try{const saved=await api('/api/time/start/',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(payload)});state.activeTimeEntry=saved;state.data.timeEntries.unshift(saved);renderShell();toast('Arbeitszeit wurde gestartet.');}catch(error){setBusy(form,false,error.message,true);toast(error.message,'error');}}
async function stopTime(event){event.preventDefault();const form=event.currentTarget;const payload=formPayload(form);payload.break_minutes=Number(payload.break_minutes||0);setBusy(form,true,'Arbeitszeit wird beendet …');try{const saved=await api('/api/time/stop/',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(payload)});upsert(state.data.timeEntries,saved);state.activeTimeEntry=null;renderShell();toast('Arbeitszeit wurde beendet und gespeichert.');}catch(error){setBusy(form,false,error.message,true);toast(error.message,'error');}}
function documentPayload(form){const data=formPayload(form);const descriptions=[...form.querySelectorAll('[name="item_description"]')];data.project=Number(data.project);data.items=descriptions.map((input,index)=>({description:input.value.trim(),quantity:form.querySelectorAll('[name="item_quantity"]')[index].value,unit:form.querySelectorAll('[name="item_unit"]')[index].value.trim(),unit_price:form.querySelectorAll('[name="item_unit_price"]')[index].value,tax_rate:form.querySelectorAll('[name="item_tax_rate"]')[index].value}));return data;}
async function saveDocument(event){event.preventDefault();const form=event.currentTarget;const payload=documentPayload(form);if(!payload.items.length||payload.items.some(i=>!i.description)){toast('Bitte mindestens eine vollständige Position eintragen.','error');return;}setBusy(form,true,'Dokument wird gespeichert …');try{const id=state.editingId;const saved=await api(`/api/mobile/commercial/${state.documentKind}/${id?`${id}/`:''}`,{method:id?'PATCH':'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(payload)});upsert(documentCollection(),saved);state.selectedDocumentId=saved.id;state.editingId=null;state.route='document-detail';renderShell();toast(state.documentKind==='invoice'?'Rechnung wurde gespeichert.':'Angebot wurde gespeichert.');}catch(error){setBusy(form,false,error.message,true);toast(error.message,'error');}}
async function saveExpense(event){event.preventDefault();const form=event.currentTarget;const payload=formPayload(form);payload.amount_net=Number(payload.amount_net);payload.tax_rate=Number(payload.tax_rate);payload.paid=form.querySelector('[name="paid"]').checked;if(payload.project)payload.project=Number(payload.project);else payload.project=null;setBusy(form,true,'Ausgabe wird gespeichert …');try{const saved=await api('/api/expenses/',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(payload)});upsert(state.data.expenses,saved);state.route='expenses';renderShell();toast('Ausgabe wurde gespeichert.');}catch(error){setBusy(form,false,error.message,true);toast(error.message,'error');}}

function bindActions() {
  document.querySelectorAll('[data-route]').forEach(button => button.addEventListener('click',()=>{state.route=button.dataset.route;renderShell();window.scrollTo(0,0);}));
  document.querySelectorAll('[data-scan-project]').forEach(button=>button.addEventListener('click',()=>{state.route='scanner';renderShell();const select=document.querySelector('#scan-project');if(select)select.value=button.dataset.scanProject;}));
  document.querySelector('[data-start-scan]')?.addEventListener('click',()=>startScan(document.querySelector('#scan-project')?.value));
  document.querySelector('[data-pending-scans]')?.addEventListener('click',listPending);
  document.querySelector('[data-logout]')?.addEventListener('click',()=>logout(true));
  document.querySelector('[data-time-start-form]')?.addEventListener('submit',startTime);
  document.querySelector('[data-time-stop-form]')?.addEventListener('submit',stopTime);
  document.querySelectorAll('[data-customer-id]').forEach(button=>button.addEventListener('click',()=>{state.selectedCustomerId=Number(button.dataset.customerId);state.route='customer-detail';renderShell();}));
  document.querySelectorAll('[data-project-id]').forEach(button=>button.addEventListener('click',()=>{state.selectedProjectId=Number(button.dataset.projectId);state.route='project-detail';renderShell();}));
  document.querySelectorAll('[data-appointment-id]').forEach(button=>button.addEventListener('click',()=>{state.selectedAppointmentId=Number(button.dataset.appointmentId);state.route='appointment-detail';renderShell();}));
  document.querySelectorAll('[data-task-id]').forEach(button=>button.addEventListener('click',()=>{state.selectedTaskId=Number(button.dataset.taskId);state.route='task-detail';renderShell();}));
  document.querySelectorAll('[data-task-status]').forEach(button=>button.addEventListener('click',()=>updateTaskStatus(button.dataset.taskStatus)));
  document.querySelectorAll('[data-document-id]').forEach(button=>button.addEventListener('click',()=>{state.selectedDocumentId=Number(button.dataset.documentId);state.route='document-detail';renderShell();}));
  document.querySelector('[data-new-customer]')?.addEventListener('click',()=>{state.editingId=null;state.route='customer-form';renderShell();});
  document.querySelector('[data-edit-customer]')?.addEventListener('click',()=>{state.editingId=state.selectedCustomerId;state.route='customer-form';renderShell();});
  document.querySelector('[data-new-project]')?.addEventListener('click',()=>{state.editingId=null;state.selectedCustomerId=null;state.route='project-form';renderShell();});
  document.querySelector('[data-new-project-for-customer]')?.addEventListener('click',()=>{state.editingId=null;state.route='project-form';renderShell();});
  document.querySelector('[data-edit-project]')?.addEventListener('click',()=>{state.editingId=state.selectedProjectId;state.route='project-form';renderShell();});
  document.querySelector('[data-new-appointment]')?.addEventListener('click',()=>{state.editingId=null;state.route='appointment-form';renderShell();});
  document.querySelector('[data-edit-appointment]')?.addEventListener('click',()=>{state.editingId=state.selectedAppointmentId;state.route='appointment-form';renderShell();});
  document.querySelector('[data-work-report]')?.addEventListener('click',()=>{state.route='work-report';renderShell();});
  document.querySelector('[data-open-map]')?.addEventListener('click',()=>{const location=selectedAppointment()?.location;if(location)window.open(`https://maps.apple.com/?q=${encodeURIComponent(location)}`,'_blank');});
  document.querySelector('[data-cancel-entity]')?.addEventListener('click',()=>{state.editingId=null;state.route=state.selectedProjectId?'project-detail':state.selectedCustomerId?'customer-detail':'home';renderShell();});
  document.querySelector('[data-customer-form]')?.addEventListener('submit',saveCustomer);
  document.querySelector('[data-project-form]')?.addEventListener('submit',saveProject);
  document.querySelector('[data-appointment-form]')?.addEventListener('submit',saveAppointment);
  document.querySelector('[data-work-report-form]')?.addEventListener('submit',saveWorkReport);
  document.querySelector('[data-cancel-appointment]')?.addEventListener('click',()=>{state.editingId=null;state.route=state.selectedAppointmentId?'appointment-detail':'appointments';renderShell();});
  document.querySelector('[data-cancel-report]')?.addEventListener('click',()=>{state.route='appointment-detail';renderShell();});
  document.querySelector('[data-new-document]')?.addEventListener('click',()=>{state.editingId=null;state.route='document-form';renderShell();});
  document.querySelector('[data-edit-document]')?.addEventListener('click',()=>{state.editingId=state.selectedDocumentId;state.route='document-form';renderShell();});
  document.querySelector('[data-cancel-document]')?.addEventListener('click',()=>{state.editingId=null;state.route=state.selectedDocumentId?'document-detail':state.documentKind==='invoice'?'invoices':'quotes';renderShell();});
  document.querySelector('[data-add-position]')?.addEventListener('click',()=>{const container=document.querySelector('[data-positions]');container?.insertAdjacentHTML('beforeend',positionEditor());const button=container?.lastElementChild?.querySelector('[data-remove-position]');button?.addEventListener('click',()=>button.closest('.position-edit')?.remove());});
  document.querySelectorAll('[data-remove-position]').forEach(button=>button.addEventListener('click',()=>{const positions=document.querySelectorAll('.position-edit');if(positions.length===1)return toast('Mindestens eine Position ist erforderlich.','error');button.closest('.position-edit')?.remove();}));
  document.querySelector('[data-new-expense]')?.addEventListener('click',()=>{state.route='expense-form';renderShell();});
  document.querySelector('[data-document-form]')?.addEventListener('submit',saveDocument);
  document.querySelector('[data-expense-form]')?.addEventListener('submit',saveExpense);
}

window.addEventListener('online',()=>{state.online=true;toast('Verbindung wiederhergestellt. Daten werden synchronisiert.','info');if(state.user)bootstrap();else renderLogin();});
window.addEventListener('offline',()=>{state.online=false;renderShell();toast('Offline-Modus aktiviert. Gespeicherte Daten bleiben lesbar.','info');});
if (state.token && state.user) bootstrap(); else renderLogin();
